<?php

// Load Nette Framework or autoloader generated by Composer
require dirname(__FILE__) . '/../libs/autoload.php';


$configurator = new Configurator;

// Enable Nette Debugger for error visualisation & logging
//$configurator->setDebugMode( FALSE );
$configurator->enableDebugger(dirname(__FILE__) . '/../log');

// Enable RobotLoader - this will load all classes automatically
$configurator->setTempDirectory(dirname(__FILE__) . '/../temp');
$configurator->createRobotLoader()
	->addDirectory(dirname(__FILE__))
	->addDirectory(dirname(__FILE__) . '/../libs')
	->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(dirname(__FILE__) . '/config/config.neon', Configurator::NONE);
$configurator->addConfig(dirname(__FILE__) . '/config/application.neon');
//$configurator->addConfig(dirname(__FILE__) . '/config/config.local.neon', Configurator::NONE); // none section
$container = $configurator->createContainer();

Form::extensionMethod('Form::addDatePicker', callback('DatePicker', 'addDatePicker'));
Form::extensionMethod('Form::addDateTimePicker', callback('DateTimePicker', 'addDateTimePicker'));

return $container;
